# Generated by Django 4.0.1 on 2022-01-31 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0006_alter_watchlist_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('-created_at',)},
        ),
    ]
